<?php

namespace EntityMarshal\Convert;

require_once dirname(__FILE__) . '/../../../../src/EntityMarshal/Convert/AbstractConvert.php';

/**
 * Test class for AbstractConvert.
 * Generated by PHPUnit on 2012-09-23 at 21:47:02.
 */
class AbstractConvertTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var AbstractConvert
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new AbstractConvert;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

}

?>
