<?php

namespace EntityMarshal\Convert;

require_once dirname(__FILE__) . '/../../../../src/EntityMarshal/Convert/Dump.php';

/**
 * Test class for Dump.
 * Generated by PHPUnit on 2012-09-23 at 21:47:01.
 */
class DumpTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Dump
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Dump;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers EntityMarshal\Convert\Dump::convert
     * @todo Implement testConvert().
     */
    public function testConvert()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}


