<?php

namespace EntityMarshal\Convert;

require_once dirname(__FILE__) . '/../../../../src/EntityMarshal/Convert/Hash.php';

/**
 * Test class for Hash.
 * Generated by PHPUnit on 2012-09-23 at 21:47:02.
 */
class HashTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Hash
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Hash(Hash::HASH_TYPE_SHA256, 'prefix', 'suffix', array('var3'));
    }

    public function testConstruct()
    {
        $this->object = new Hash(Hash::HASH_TYPE_SHA256, 'prefix', 'suffix', array('var3'));
    }

    /**
     * @covers EntityMarshal\Convert\Hash::convert
     * @todo Implement testConvert().
     */
    public function testConvert()
    {
        $actual = $this->object->convert(new \ConcreteEntity());
        $this->assertRegExp('/^[a-fA-F0-9]{64}$/', $actual);
    }


}


