<?php

namespace EntityMarshal\Convert;

require_once dirname(__FILE__) . '/../../../../src/EntityMarshal/Convert/Json.php';

/**
 * Test class for Json.
 * Generated by PHPUnit on 2012-09-23 at 21:47:03.
 */
class JsonTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Json
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Json(false);
    }

    public function testConstruct()
    {
        $this->object = new Json(false);
    }

    /**
     * @covers EntityMarshal\Convert\Json::convert
     * @todo Implement testConvert().
     */
    public function testConvert()
    {
        $json = $this->object->convert(new \ConcreteEntity);

        $actual = json_decode($json);

        $this->assertInstanceOf('\stdClass', $actual);
    }

}


