<?php

namespace EntityMarshal\Convert;

use EntityMarshal\Convert\QueryString;
/**
 * Test class for QueryString.
 * Generated by PHPUnit on 2012-09-23 at 21:47:04.
 */
class QueryStringTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var QueryString
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new QueryString(array('var3'));
    }

    public function testConstruct()
    {
        $this->object = new QueryString(array('var3'));
    }

    public function testConvert()
    {
        $qs = $this->object->convert(new \ConcreteEntity);

        $this->assertNotEmpty($qs);
    }

}


