<?php

namespace EntityMarshal;

require_once dirname(__FILE__) . '/../../../src/EntityMarshal/AbstractMarshaledEntity.php';

/**
 * Test class for AbstractMarshaledEntity.
 * Generated by PHPUnit on 2012-09-23 at 21:46:45.
 */
class AbstractMarshaledEntityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var AbstractMarshaledEntity
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new AbstractMarshaledEntity;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers EntityMarshal\AbstractMarshaledEntity::set
     * @todo Implement testSet().
     */
    public function testSet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EntityMarshal\AbstractMarshaledEntity::fromArray
     * @todo Implement testFromArray().
     */
    public function testFromArray()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EntityMarshal\AbstractMarshaledEntity::getRuntimeCache
     * @todo Implement testGetRuntimeCache().
     */
    public function testGetRuntimeCache()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EntityMarshal\AbstractMarshaledEntity::typeof
     * @todo Implement testTypeof().
     */
    public function testTypeof()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}


