<?php

namespace EntityMarshal;

require_once dirname(__FILE__) . '/../../../src/EntityMarshal/ForeignScope.php';

/**
 * Test class for ForeignScope.
 * Generated by PHPUnit on 2012-09-23 at 21:46:43.
 */
class ForeignScopeTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var string
     */
    public $testVar1 = 'sage tea';

    /**
     * @var ForeignScope
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object   = ForeignScope::getInstance();
        $this->testVar1 = 'regular boring tea';
    }

    /**
     * @covers EntityMarshal\ForeignScope::getInstance
     * @covers EntityMarshal\ForeignScope::__construct
     */
    public function testGetInstance()
    {
        $this->object = ForeignScope::getInstance();

        $this->assertInstanceOf(
            '\EntityMarshal\ForeignScope',
            $this->object
        );
    }

    /**
     * @covers EntityMarshal\ForeignScope::getObjectVars
     */
    public function testGetObjectVars()
    {
        $this->assertEquals(
            array(
                'testVar1' => 'regular boring tea',
            ),
            $this->object->getObjectVars($this)
        );
    }

    /**
     * @covers EntityMarshal\ForeignScope::getClassVars
     */
    public function testGetClassVars()
    {
        $this->assertEquals(
            array(
                'testVar1' => 'sage tea',
            ),
            $this->object->getClassVars(__CLASS__)
        );
    }

}

