<?php

namespace EntityMarshalExample;

require_once dirname(__FILE__) . '/../../../examples/EntityMarshalExample/DynamicClassMethodMarshaledEntity.php';

/**
 * Test class for DynamicClassMethodMarshaledEntity.
 * Generated by PHPUnit on 2012-09-23 at 21:49:53.
 */
class DynamicClassMethodMarshaledEntityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var DynamicClassMethodMarshaledEntity
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DynamicClassMethodMarshaledEntity;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

}


