<?php

namespace EntityMarshalExample;

require_once dirname(__FILE__) . '/../../../examples/EntityMarshalExample/DynamicHybridMarshaledEntity.php';

/**
 * Test class for DynamicHybridMarshaledEntity.
 * Generated by PHPUnit on 2012-09-23 at 21:49:56.
 */
class DynamicHybridMarshaledEntityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var DynamicHybridMarshaledEntity
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new DynamicHybridMarshaledEntity;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

}


