<?php

namespace EntityMarshalExample;

require_once dirname(__FILE__) . '/../../../examples/EntityMarshalExample/StdHybridMarshaledEntity.php';

/**
 * Test class for StdHybridMarshaledEntity.
 * Generated by PHPUnit on 2012-09-23 at 21:49:53.
 */
class StdHybridMarshaledEntityTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var StdHybridMarshaledEntity
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new StdHybridMarshaledEntity;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers EntityMarshalExample\StdHybridMarshaledEntity::setTestBool
     * @todo Implement testSetTestBool().
     */
    public function testSetTestBool()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EntityMarshalExample\StdHybridMarshaledEntity::setTestString
     * @todo Implement testSetTestString().
     */
    public function testSetTestString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    public function testDefaultProperties()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    public function testSetter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    public function testGetter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
}

