<?php

namespace EntityMarshalExample;

require_once dirname(__FILE__) . '/../../../examples/EntityMarshalExample/StdHybridEntity.php';

/**
 * Test class for StdHybridEntity.
 * Generated by PHPUnit on 2012-09-23 at 21:49:55.
 */
class StdHybridEntityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var StdHybridEntity
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new StdHybridEntity;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers EntityMarshalExample\StdHybridEntity::setTestBool
     * @todo Implement testSetTestBool().
     */
    public function testSetTestBool()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EntityMarshalExample\StdHybridEntity::setTestString
     * @todo Implement testSetTestString().
     */
    public function testSetTestString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
