<?php

namespace EntityMarshalExample;

require_once dirname(__FILE__) . '/../../../examples/EntityMarshalExample/StdObjectPropertyMarshaledEntity.php';

/**
 * Test class for StdObjectPropertyMarshaledEntity.
 * Generated by PHPUnit on 2012-09-23 at 21:49:52.
 */
class StdObjectPropertyMarshaledEntityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var StdObjectPropertyMarshaledEntity
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new StdObjectPropertyMarshaledEntity;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

}

?>
