<?php

namespace EntityMarshal\Exception;

require_once dirname(__FILE__) . '/../../../../src/EntityMarshal/Exception/RuntimeException.php';

/**
 * Test class for RuntimeException.
 * Generated by PHPUnit on 2012-09-23 at 21:34:54.
 */
class RuntimeExceptionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var RuntimeException
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RuntimeException;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

}


