<?php

namespace EntityMarshal\Entity\Marshaled;

require_once dirname(__FILE__) . '/../../../../../src/EntityMarshal/Entity/Marshaled/ClassMethodEntity.php';

/**
 * Test class for ClassMethodEntity.
 * Generated by PHPUnit on 2012-09-23 at 21:47:09.
 */
class ClassMethodEntityTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var ClassMethodEntity
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();

        /* @var $stub PHPUnit_Framework_MockObject_MockObject */

        $stub = $this->getMockForAbstractClass(
            '\EntityMarshal\Entity\ClassMethodEntity'
        );

        $this->object = $stub;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers EntityMarshal\Entity\Marshaled\ClassMethodEntity::calledClassName
     * @todo Implement testCalledClassName().
     */
    public function testCalledClassName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EntityMarshal\Entity\Marshaled\ClassMethodEntity::__call
     * @todo Implement test__call().
     */
    public function test__call()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}


