<?php

namespace EntityMarshal\Definition;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-18 at 15:20:47.
 */
class PropertyCollectionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var PropertyCollection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new PropertyCollection;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers EntityMarshal\Definition\PropertyCollection::add
     * @todo   Implement testAdd().
     */
    public function testAdd()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EntityMarshal\Definition\PropertyCollection::import
     * @todo   Implement testImport().
     */
    public function testImport()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers EntityMarshal\Definition\PropertyCollection::export
     * @todo   Implement testExport().
     */
    public function testExport()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
