<?php

namespace EntityMarshal\RuntimeCache;

/**
 * Test class for RuntimeCacheSingleton.
 * Generated by PHPUnit on 2012-09-23 at 21:46:46.
 */
class RuntimeCacheSingletonTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @return RuntimeCacheInterface
     */
    public function testGetInstance()
    {
        $object = RuntimeCacheSingleton::getInstance();

        $this->assertInstanceOf(
            '\EntityMarshal\RuntimeCache\RuntimeCacheInterface',
            $object
        );

        return $object;
    }

    /**
     * @depends testGetInstance
     */
    public function testGetInstanceAgain(RuntimeCacheInterface $object)
    {
        $actual = RuntimeCacheSingleton::getInstance();

        $this->assertEquals($object, $actual);
    }
}


