<?php

namespace EntityMarshal\RuntimeCache;

require_once dirname(__FILE__) . '/../../../../src/EntityMarshal/RuntimeCache/RuntimeCacheSingleton.php';

/**
 * Test class for RuntimeCacheSingleton.
 * Generated by PHPUnit on 2012-09-23 at 21:46:46.
 */
class RuntimeCacheSingletonTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * @covers EntityMarshal\RuntimeCache\RuntimeCacheSingleton::getInstance
     * @covers EntityMarshal\RuntimeCache\RuntimeCacheSingleton::__construct
     */
    public function testGetInstance()
    {
        $object = RuntimeCacheSingleton::getInstance();

        $this->assertInstanceOf(
            '\EntityMarshal\RuntimeCache\RuntimeCacheSingleton',
            $object
        );
    }

    /**
     * @covers EntityMarshal\RuntimeCache\RuntimeCacheSingleton::getScope
     */
    public function testGetScope()
    {
        $object = RuntimeCacheSingleton::getInstance();

        $this->assertEquals(
            RuntimeCacheSingleton::SCOPE_DEFAULT,
            $object->getScope()
        );
    }

    /**
     * @covers EntityMarshal\RuntimeCache\RuntimeCacheSingleton::setScope
     */
    public function testSetScope()
    {
        $object = RuntimeCacheSingleton::getInstance();

        $this->assertEquals(
            $object,
            $object->setScope(__CLASS__)
        );

        $this->assertEquals(
            __CLASS__,
            $object->getScope()
        );
    }


    /**
     * @covers EntityMarshal\RuntimeCache\RuntimeCacheSingleton::clearScope
     * @covers EntityMarshal\RuntimeCache\RuntimeCacheSingleton::setScope
     */
    public function testClearScope()
    {
        $object = RuntimeCacheSingleton::getInstance();

        $this->assertEquals(
            $object,
            $object->setScope()
        );

        $this->assertEquals(
            RuntimeCacheSingleton::SCOPE_DEFAULT,
            $object->getScope()
        );

        $object->setScope(__CLASS__);

        $this->assertEquals(
            __CLASS__,
            $object->getScope()
        );

        $this->assertEquals(
            $object,
            $object->clearScope()
        );

        $this->assertEquals(
            RuntimeCacheSingleton::SCOPE_DEFAULT,
            $object->getScope()
        );
    }

    /**
     * @covers EntityMarshal\RuntimeCache\RuntimeCacheSingleton::set
     */
    public function testSet()
    {
        $object = RuntimeCacheSingleton::getInstance();

        $this->assertEquals(
            RuntimeCacheSingleton::SCOPE_DEFAULT,
            $object->getScope()
        );

        $this->assertEquals(
            $object,
            $object->set('testSet', 'in the middle of the night')
        );

        $this->assertEquals(
            $object,
            $object->set('testSet', 'i\'ll be walking in my sleep', __CLASS__)
        );
    }

    /**
     * @covers EntityMarshal\RuntimeCache\RuntimeCacheSingleton::get
     */
    public function testGet()
    {
        $object = RuntimeCacheSingleton::getInstance();

        $this->assertEquals(
            'in the middle of the night',
            $object->get('testSet')
        );

        $this->assertEquals(
            'i\'ll be walking in my sleep',
            $object->get('testSet', __CLASS__)
        );
    }

    /**
     * @covers EntityMarshal\RuntimeCache\RuntimeCacheSingleton::has
     */
    public function testHas()
    {
        $object = RuntimeCacheSingleton::getInstance();

        $this->assertTrue($object->has('testSet'));

        $this->assertTrue($object->has('testSet', __CLASS__));

        $this->assertFalse($object->has('bacon'));
    }

    /**
     * @covers EntityMarshal\RuntimeCache\RuntimeCacheSingleton::remove
     */
    public function testRemove()
    {
        $object = RuntimeCacheSingleton::getInstance();

        $this->assertEquals(
            $object,
            $object->remove('testSet')
        );

        $this->assertEquals(
            $object,
            $object->remove('testSet', __CLASS__)
        );

        $this->assertFalse($object->has('testSet'));

        $this->assertFalse($object->has('testSet', __CLASS__));
    }

    /**
     * @covers EntityMarshal\RuntimeCache\RuntimeCacheSingleton::serialize
     */
    public function testSerialize()
    {
        $object = RuntimeCacheSingleton::getInstance();
        
        $object->set('testSerialize', 'on the global scope');
        $object->set('testSerialize', 'on the class scope', __CLASS__);

        $this->assertNotEmpty($cereal = serialize($object));

        return $cereal;
    }

    /**
     * @covers EntityMarshal\RuntimeCache\RuntimeCacheSingleton::unserialize
     * @depends testSerialize
     */
    public function testUnserialize($cereal)
    {
        $object = unserialize($cereal);

        $this->assertTrue($object->has('testSerialize'));
        $this->assertTrue($object->has('testSerialize', __CLASS__));

        $this->assertEquals(
            'on the global scope',
            $object->get('testSerialize')
        );

        $this->assertEquals(
            'on the class scope',
            $object->get('testSerialize', __CLASS__)
        );
    }

}


